In [1]:
import numpy as np
import random

from connect4 import ConnectFourEnv

In [2]:
def seed(seed):
    random.seed(seed)
    np.random.seed(seed)

In [4]:
seed(1234)
env = ConnectFourEnv()
	
env.reset()

print(env.display_board())

temp_board = np.zeros((6,7))
temp_board[0,5] = 1
temp_board[1,5] = 1
temp_board[2,5] = 1



env.load_game_board(temp_board)

print(env.display_board())

next_state, reward, done, _  = env.step(5,1)

print(reward)
print(env.display_board())


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
done
